name: Cargo Build & Test

on:
  push:
    tags:
      - 'v*'  # 當推送 tag（如 v1.0.0）時觸發

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project - latest
    strategy:
      matrix:
        toolchain:
          - stable
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on:	${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build project
        run: |
          cargo build --release
          mkdir -p dist
          if [[ "${{ matrix.platform }}" == "ubuntu-latest" ]]; then
            mv target/release/socksproxy dist/socksproxy-x64
          else
            mv target/release/socksproxy dist/socksproxy-macos
          fi
      - run: cargo test --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-artifact
          path: dist/
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-artifact
          path: artifacts/ubuntu

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-artifact
          path: artifacts/macos
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Release files
          files: |
            artifacts/ubuntu/socksproxy-x64
            artifacts/macos/socksproxy-macos