name: Cargo Build & Test

on:
  push:
    tags:
      - 'v*'  # 當推送 tag（如 v1.0.0）時觸發

env: 
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Rust project - latest
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - name: Verify binary file exists
        run: ls -lh target/debug/socksproxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            body contents
          files: target/debug/socksproxy