name: Cargo Build & Test

on:
  push:
    tags:
      - 'v*'  # 當推送 tag（如 v1.0.0）時觸發

env: 
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Rust project - latest
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: read
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - name: Verify binary file exists
        run: ls -lh target/debug/socksproxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: my_tag

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_GITHUB_TOKENh: target/debug/socksproxy
          asset_name: socksproxy
          asset_content_type: application/octet-stream